services:
# App
    ebike.web:
        container_name: ebike.web
        image: ${ROOT_REGISTRY}/ebike.web
        build:
          context: .
          dockerfile: src/Frontend/eBike.Web/Dockerfile

    ebike.aggregator.bff:
        container_name: ebike.aggregator.bff
        image: ${ROOT_REGISTRY}/ebike.aggregator.bff
        build:
            context: .
            dockerfile: src/Aggregators/eBike.BFF.Aggregator/Dockerfile
        environment:
            APPID_USERS: ${APPID_USERS}
            APPID_BIKES: ${APPID_BIKES}

    ebike.service.bikes:
        container_name: ebike.service.bikes
        image: ${ROOT_REGISTRY}/ebike.service.bikes
        build:
          context: .
          dockerfile: src/Services/eBike.Services.Bikes/Dockerfile
        environment:
            ConnectionString : ${MONGO_CONNECTIONSTRING}
            PUBSUB_NAME: ${PUBSUB_NAME}

    ebike.service.users:
        container_name: ebike.service.users
        image: ${ROOT_REGISTRY}/ebike.service.users
        build:
            context: .
            dockerfile: src/Services/eBike.Services.Users/Dockerfile
        environment:
            ConnectionString : ${MONGO_CONNECTIONSTRING}
            PUBSUB_NAME: ${PUBSUB_NAME}
            USER_STATE_NAME: ${USER_STATE_NAME}

    ebike.worker.processing:
        container_name: ebike.worker.processing
        image: ${ROOT_REGISTRY}/ebike.worker.processing
        build:
            context: .
            dockerfile: src/Workers/eBike.Workers.Processing/Dockerfile
# App

# Container Dapperizzati
    ebike.web-dapr:
        container_name: ebike.web-dapr
        image: "daprio/daprd:${DAPRD_TAG}"
        network_mode: "service:ebike.web" # stessa rete del container da dapperizzare
        command: ["./daprd",
            "-app-id", "${APPID_WEB}",
            "-app-port", "80",
            "--log-level", "debug",
            "-components-path", "/components",
            "-config", "/configurations/config.yaml"
          ]
        volumes:
            - "${DAPR_COMPONENTS_FOLDER}:/components"
            - "./dapr/configurations/:/configurations"
        depends_on:
            - ebike.web
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 100M

    ebike.service.bikes-dapr:
        container_name: ebike.service.bikes-dapr
        image: "daprio/daprd:${DAPRD_TAG}"
        network_mode: "service:ebike.service.bikes" # stessa rete del container da dapperizzare
        command: ["./daprd",
            "-app-id", "${APPID_BIKES}",
            "-app-port", "80",
            "--log-level", "debug",
            "--app-protocol", "grpc",
            "-components-path", "/components",
            "-config", "/configurations/config.yaml"
          ]
        volumes:
            - "${DAPR_COMPONENTS_FOLDER}:/components"
            - "./dapr/configurations/:/configurations"
        depends_on:
            - ebike.service.bikes
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 100M

    ebike.service.users-dapr:
        container_name: ebike.service.users-dapr
        image: "daprio/daprd:${DAPRD_TAG}"
        network_mode: "service:ebike.service.users" # stessa rete del container da dapperizzare
        command: ["./daprd",
            "-app-id", "${APPID_USERS}",
            "-app-port", "80",
            "--log-level", "debug",
            "-components-path", "/components",
            "-config", "/configurations/config.yaml"
          ]
        volumes:
            - "${DAPR_COMPONENTS_FOLDER}:/components"
            - "./dapr/configurations/:/configurations"
        depends_on:
            - ebike.service.users
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 100M

    ebike.worker.processing-dapr:
        container_name: ebike.worker.processing-dapr
        image: "daprio/daprd:${DAPRD_TAG}"
        network_mode: "service:ebike.worker.processing" # stessa rete del container da dapperizzare
        command: ["./daprd",
            "-app-id", "${APPID_PROCESSING}",
            "-app-port", "80",
            "--log-level", "debug",
            "-components-path", "/components",
            "-config", "/configurations/config.yaml"
          ]
        volumes:
            - "${DAPR_COMPONENTS_FOLDER}:/components"
            - "./dapr/configurations/:/configurations"
        depends_on:
            - ebike.worker.processing
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 100M

    ebike.aggregator.bff-dapr:
        container_name: ebike.aggregator.bff-dapr
        image: "daprio/daprd:${DAPRD_TAG}"
        network_mode: "service:ebike.aggregator.bff" # stessa rete del container da dapperizzare
        command: ["./daprd",
            "-app-id", "${APPID_AGGREGATOR}",
            "-app-port", "80",
            "--log-level", "debug",
            "-components-path", "/components",
            "-config", "/configurations/config.yaml"
          ]
        volumes:
            - "${DAPR_COMPONENTS_FOLDER}:/components"
            - "./dapr/configurations/:/configurations"
        depends_on:
            - ebike.aggregator.bff
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 100M

# Container Dapperizzati

# Services
    redis:
        container_name: redis
        image: redis:alpine
        ports:
        - "6379:6379"
        command: redis-server --requirepass redisPassword

    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
          MONGO_INITDB_ROOT_USERNAME: dapr
          MONGO_INITDB_ROOT_PASSWORD: daprPassword
        ports:
        - 27017:27017
        restart: unless-stopped
        volumes:
            - ./mongodb/database:/data/db
# Services

# Observability
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin-slim
        ports:
        - "9411:9411"

# Observability