name: ebike
extensions:
- name: dapr
  log-level: debug  
  config: ./dapr/configurations/config  
  # components-path configures the components path of the dapr sidecard
  components-path: "./dapr/components/"
services:
- name: ebike-web
  project: src/Frontend/eBike.Web/eBike.Web.csproj
  bindings:
  - protocol: https
    containerPort: 443
- name: ebike-aggregator-bff
  project: src/Aggregators/eBike.BFF.Aggregator/eBike.BFF.Aggregator.csproj
  env:
  - name: APPID_USERS
    value: ${APPID_USERS}
  - name: APPID_BIKES
    value: ${APPID_BIKES}
- name: ebike-service-bikes
  project: src/Services/eBike.Services.Bikes/eBike.Services.Bikes.csproj
  env:
  - name: ConnectionString
    value: ${MONGO_CONNECTIONSTRING}
  - name: PUBSUB_NAME
    value: ${PUBSUB_NAME}
- name: ebike-service-users
  project: src/Services/eBike.Services.Users/eBike.Services.Users.csproj
  env:
  - name: ConnectionString
    value: ${MONGO_CONNECTIONSTRING}
  - name: PUBSUB_NAME
    value: ${PUBSUB_NAME}
  - name: USER_STATE_NAME
    value: ${USER_STATE_NAME}
- name: ebike-worker-cron-processing
  project: src/Workers/eBike.Worker.Cron.Processing/eBike.Worker.Cron.Processing.csproj
  env:
  - name: ConnectionString
    value: ${MONGO_CONNECTIONSTRING}
  - name: AZURE_MAPS_KEY
    value: ${AZURE_MAPS_KEY}
- name: redis
  image: redis:alpine
  bindings:
  - port: 6379
    containerPort: 6379
    protocol: http
- name: mongodb
  image: mongo:latest
  bindings:
  - port: 27017
    containerPort: 27017
    protocol: http
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: dapr
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: daprPassword
- name: zipkin
  image: openzipkin/zipkin-slim
  bindings:
  - port: 9411
    containerPort: 9411
    protocol: http