apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-state
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
#---
#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: bike-state
#  namespace: default
#spec:
#  type: state.redis
#  version: v1
#  metadata:
#  - name: redisHost
#    value: redis:6379
#  - name: redisPassword
#    value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bike-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""